### ISSUE TITLE
Problem with keyboard shortcuts

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#10]
When I plot in new tags, I often switch between my browser (Chrome) and a text editor to copy and paste the tags. When I do this, I have problems with the keyboard shortcuts:
1. I am unable to uncheck readings using the number keys. The reading is highlighted, but it doesn't uncheck.
2. When I press space, I don't get the next word, but the one after that.
The shortcuts work properly if I refresh.

**Comment by andrely** [comment]
Fixed in commit c1c1c13275886eb807692e84351798c913f5071e.
