### ISSUE TITLE
downcase and OBT wordforms

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#12]
In the current version, OBT wordforms are completely downcased. According to tje OBT standard, however, only the first letter of a token is downcased: "UNESCO-konvensjonane" should be "&#60;uNESCO-konvensjonane&#62;", not "&#60;unesco-convensjonane&#62;". There are probably very few, if any, cg-rules for which this matters, but it might be a good idea to change this for consistency.

**Comment by andrely** [comment]
Fixed cfc976e432b3ecfab6e1fc71a6ebc44d03d6fc81.
