### ISSUE TITLE
Keyboard shortcuts for adding wordforms and tags.

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#15]
It would be great if there were keyboard shortcuts for activating the "add tag" and "change word" fields! Now we can do most of the disambiguation without leaving the keyboard, which is very effective, and with these extra shortcut  we could do without the mouse alltogether.

**Comment by andrely** [comment]
Added in efdf9efbf7a7c3da8be2bb6b95517e64df8b77a0.
