### ISSUE TITLE
Problem with sentence split

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#17]
There should be a sentence split after characters such as .,!,?,... . However, in the following example, the quotation mark following the final stop is included in the sentence:

Sentence 87 from "nou_001"

Det kan heller ikke være tvil om at for store deler av folket står også uttrykket " folkekirken " for en kirke hvor mennesker får ta del i kirkelige handlinger som dåp , konfirmasjon og vigsel uten at det stilles krav til deres personlige trosforhold . "

**Comment by andrely** [comment]
The <<< marker on the "." token is added by CG rules, and are not put there by the multitagger.

I'll check if this is a problem with the OBT ruleset first.

**Comment by andrely** [comment]
I will add an option to segment files by "<<<" delimiter or OBT token delimiters.

**Comment by andrely** [comment]
Option add in f505fc879823a6c7be26a9fdb1258cd65681dd86
