### ISSUE TITLE
Error when changing a word form

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#21]
After the last "update" of Tag-annotator I get an error message when I click on "Change word" + "Change":

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

(If you're the administrator of this website, then please read the log file "production.log" to find out what went wrong.)

**Comment by andrely** [comment]
Fixed in 6ff06d38412126c865b7171fbd17f434f91e9332.
