### ISSUE TITLE
prevent new words with no content

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#22]
When creating a new word using "Insert word" I have several times forgotten to fill in the "New word:"-field. When I do this, a new token without any content is created. This is an easy mistake to do, but a difficult one to discover afterwords. It would be nice if we got some kind of error message if we try to submit a word without a word form.

**Comment by andrely** [comment]
Fixed in b0608ce6e5afc9df48c9cfa29be622b688b378de.
