### ISSUE TITLE
Sentence doesn't split after "|"

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#6]
The token "<|>" "$|" clb <overskrift> <<< should be sentence-final, but it isn't now:

Sentence 85 from "aftenposten_014"

Museumsparadokser | | Verdensarv .

**Comment by peresolb** [comment]
Same problem with ":", but not with "?", "!" and "..."

**Comment by andrely** [comment]
Fixed in commit b160c022849ef3c41f8f3172bae7e3a6abc34857
