### ISSUE TITLE
Editing the OBT wordforms

### ISSUE THREAD

**Issue by peresolb** [andrely/tag-annotator#7]
When disambiguating OBT files, I sometimes need to edit the OBT wordform, i.e. line 2 in the following:

&lt;word&gt;sluttfasen&lt;/word&gt;
  "&lt;sluttfasen&gt;"
    "sluttfase" subst appell mask be ent

This is currently not possible in Tag-annotator.

**Comment by andrely** [comment]
Are there any cases where the xml and OBT word forms are different (except that XML preserves case) ?

Currently, changing the word changes both, i.e. what you enter is stored as the XML form and a downcased version is stored as the OBT form.

**Comment by peresolb** [comment]
In our project we sometimes need to "trick" the OBT: The syntactic module of OBT automatically places a sentence boundary after ., !, : etc. In some cases we want to prevent OBT from doing that. In those cases we need to alter the OBT wordforms (but not the XML wordforms) before running the syntactic module of OBT, as the Constraint Grammar rules contain a list of wordforms for sentence delimiters.

**Comment by andrely** [comment]
Basic interface for this added in 2a0852dd92b4e50952555cc9bb16e5b4205ed570.
